# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    name: "Build and Test"
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps: 
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Use Node 15.x
        uses: actions/setup-node@v1
        with:
            node-version: 15
      
      - name: Install dependencies
        run: npm install
      
      - name: Build 
        run: tsc --module amd
        
      - name: Lint
        run: npm run lint 
        
      - name: Test
        run: npm run test
 
